---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boss
  namespace: ead
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boss
        tier: frontend
    spec:
      containers:
      - name: boss
        image: docker.fs.usda.gov/ead/boss_api_development:$POM_VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/tomcat/logs
          name: boss-logs
          readOnly: false
        - mountPath: /usr/local/tomcat/work
          name: boss-work
          readOnly: false
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: boss-db-secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: boss-db-secret
              key: password
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: boss-db-secret
              key: connection-string
      volumes:
        - name: boss-logs
          emptyDir: {}
        - name: boss-work
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: boss-svc
  namespace: ead
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 32908
  selector:
    app: boss
    tier: frontend
