---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boss
  namespace: ead
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: boss
        tier: frontend
    spec:
      containers:
      - name: boss
        image: docker.fs.usda.gov/ead/boss_api_development:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: boss-svc
  namespace: ead
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 32908
  selector:
    app: boss
    tier: frontend
