insert into dbo.expense_codes(id, name)
 values (1, 'Common Carrier'),
        (2, 'Mileage & Parking'),
		(3, 'Rental Car'),
		(4, 'Per Diem'),
		(5, 'Misc Travel Expenses'),
		(6, 'Meeting Registration'),
		(7, 'Training, Tuition, Books'),
		(8, 'Base Salaries'),
		(9, 'Overtime'),
		(10, 'Lump Sum-A/L'),
		(11, 'Lump Sum-Comp'),
		(12, 'Lump Sum-Credit'),
		(13, 'Awards'),
		(14, 'Trailers'),
		(15, 'Campground Fees'),                                       
                (16, 'LWOP'),
		(17, 'Cooperative Research'),
		(18, 'Computer'),
		(19, 'Rent, Guard Service, RWA'),
		(21, 'Telephone'),
		(22, 'Office Services'),
		(23, 'Office Supplies'),
		(24, 'Trucks - General'),
		(25, 'WCF Trucks-F.O.R.'),
		(26, 'WCF Trucks-Mileage'),
		(27, 'GSA Trucks'),
		(28, 'Leased Trucks'),                                                        
        (29, 'Maps and Photos'),                                                        
        (30, 'Wellness/Safety'),                                                        
        (32, 'Helicopters, Boats, Outfitters'),                                         
        (33, 'Clearfield yard'),                                                        
        (34, 'ATV'),                                                                    
        (35, 'Field Equipment'),                                                        
        (20, 'Building Space Agreements'),                                              
        (37, 'TOS'),                                                                    
        (39, 'Printing'),                                                               
        (40, 'Safety Boots');                  